### ISSUE TITLE
Support for React 0.14

### ISSUE THREAD

**Issue by littlebtc** [mlmorg/react-hyperscript#10]
It seems there is no no compatibility issue with React 0.14, as I brew my own branch with modified package.json to run the test:
https://travis-ci.org/littlebtc/react-hyperscript/builds/79708057

However there is a warning about the new `react-dom` package:

    Warning: React.renderToStaticMarkup is deprecated. Please use ReactDOMServer.renderToStaticMarkup from require('react-dom/server') instead.

I am trying to write my new project on React 0.14rc1. I may report anything else if I found something go wrong.

**Comment by mlmorg** [comment]
#11 has fixed this. Thanks!
