### ISSUE TITLE
compatibility with react native

### ISSUE THREAD

**Issue by reqshark** [mlmorg/react-hyperscript#12]
that would be slick

**Comment by reqshark** [comment]
btw got it to work with the react-native demo on my iphone, but i had to do it like:

```js
var styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
});

var AwesomeProject = React.createClass({
  render: function() {
    return (
      h(View, { style: styles.container }, [
        h(Text, { style: styles.welcome }, 'hello')
      ])
    );
  }
});
``` 
replace this repo's `index.js` references: 
```js
'use strict';
var parseTag = require('virtual-hyperscript/parse-tag');
var React = require('react');
```
with:
```js
'use strict';
var parseTag = require('./parse-tag');
var React = require('react-native');

module.exports = h;
```

**Comment by kumavis** [comment]
@reqshark did you make your own `./parse-tag`?

**Comment by reqshark** [comment]
@kumavis, yea [copied it from here](https://github.com/Raynos/virtual-hyperscript/blob/master/parse-tag.js) when i added my modified react-hyperscript module... 

and TBH I don't fully know yet how react-native does it's JS packaging, like browserifyish deps

**Comment by reqshark** [comment]
juggling between a `react-native` dep and `react` seems pretty complicated. native compatibility might be unrealistic given the simple interface we expect with hyperscript, 

### so that's why i [forked it](https://github.com/reqshark/react-native-hyperscript).

unless someone can show otherwise (how to PR that) I'll just maintain [`react-native-hyperscript`](https://www.npmjs.com/package/react-native-hyperscript)

**Comment by mlmorg** [comment]
:+1: I think that makes the most sense. Will close for now unless folks have better ideas.
