### ISSUE TITLE
Global "export", no hyperscript dependency

### ISSUE THREAD

**Issue by jelz** [mlmorg/react-hyperscript#17]
For my private project I've tweaked the code to look [like this (diff)](https://github.com/jelz/react-hyperscript/compare/e7f1dc860e93194763c084b5e9255c8e4aa6d0fa...98f3982a34a33b3c15e1f89ca9f6cbe4d39079ff). Comments and suggestions warmly welcomed. If you're interested in incorporating this change to the library - let me know, I'll prepare a PR. Please close this issue otherwise.

**Comment by mlmorg** [comment]
What's the benefit of this? Your code bundler should handle this for you.
