### ISSUE TITLE
UMD version?

### ISSUE THREAD

**Issue by rsyring** [mlmorg/react-hyperscript#33]
I like the fact that Mithril can be used without build tools.  However, it's relatively obscure and my team is already familiar with React b/c we are using it for larger projects.  So, I'm trying to get a no-build React experience for small projects that would be close to what I get when including Mithril.  

I can do that by simply including React and React-Dom as scripts and avoid JSX.  However, aliasing React.createElement() still leaves much to be desired.  Therefore, I'd like to be able to include a hyperscript library as well.  This library seems like it would work, but as best I can tell, is not setup to be imported as a script into a web page.  Could you add UMD support so that it can be?

Thanks for your consideration.

**Comment by mlmorg** [comment]
If you really don't want to use a module bundler, then you can always use something like [globalify](https://github.com/KoryNunn/globalify) and run it on this module.

**Comment by PascalPixel** [comment]
React offers UMD support, the only thing that you can't use is JSX!
In comes react-hyperscr... oh wait no... 😭
