### ISSUE TITLE
Support Fragments

### ISSUE THREAD

**Issue by lo1tuma** [mlmorg/react-hyperscript#36]
Improved fragment support has been [shipped](https://reactjs.org/blog/2017/11/28/react-v16.2.0-fragment-support.html) with React 16.2.0. As there is even a special JSX syntax for fragments I thought it would be nice to also have a convenient way in `react-hyperscript` to create fragments.

-----------------

My API proposal would be the following:

**`h(listOfElements)`**

Returns a React element.

* **listOfElements** `Array` - An array of React elements that will be wrapped with `React.Fragment`.

Example:

```js
h([
    h('li', 'first'),
    h('li', 'second'),
    h('li', 'third')
]);
```

This would be equivalent to:

```js
h(React.Fragment, [
    h('li', 'first'),
    h('li', 'second'),
    h('li', 'third')
]);
```
-----------------

I would be happy to implement this if the proposal gets accepted.

**Comment by lo1tuma** [comment]
ping @mlmorg

**Comment by lo1tuma** [comment]
@mlmorg Do you have any feedback?

**Comment by mlmorg** [comment]
Sorry for the delay (holiday time)! This sounds good to me. If you're able to implement this, I would happily merge!

**Comment by lo1tuma** [comment]
Thanks for the feedback @mlmorg I’ve filed a PR to implement this proposal, see #39.
