### ISSUE TITLE
Template pre-compilation

### ISSUE THREAD

**Issue by rtsao** [mlmorg/react-hyperscript#8]
It might be nice to have a way to pre-compile templates, perhaps a sweet.js macro like Mithril uses: http://lhorie.github.io/mithril/optimizing-performance.html#compiling-templates

**Comment by roman01la** [comment]
Babel plugin would work fine here. Also since nearly every React project is using Babel it would be trivial to include a plugin into build config.

**Comment by roman01la** [comment]
FYI, I've put together Babel plugin which pre-compiles HyperScript into plain `React.createElement` calls https://github.com/roman01la/babel-plugin-react-hyperscript

**Comment by rtsao** [comment]
Wow, nice! Marking this as resolved then.
